name: Build static systemd cryptsetup on ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: sudo apt-get install -y libaio-dev autopoint libpopt-dev libjson-c-dev gperf gettext

    - name: Run make
      run: make
