name: Build static systemd cryptsetup on ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get install -y libaio-dev autopoint libpopt-dev libjson-c-dev gperf gettext autoconf-archive libcap-dev ninja-build libmbedtls-dev uuid-dev libblkid-dev libltdl-dev libmount-dev

    - name: Run make
      run: make

    - name: Archive systemd-cryptsetup
      uses: actions/upload-artifact@v4
      with:
        name: systemd-cryptsetup
        path: systemd-cryptsetup

    - name: Archive systemd-cryptenroll
      uses: actions/upload-artifact@v4
      with:
        name: systemd-cryptenroll
        path: systemd-cryptenroll
